name: First CI
on: push
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from Rushikesh to Github Actions!" > greet.txt
      - run: cat greet.txt
    steps:
      - uses: actions/checkout@v4
      - name: Show the commit
        run: echo "Commit: $GITHUB_SHA"
      - run: ls -la
